<?php

/**
 * @file
 * Contains media_entity_ustudio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function media_entity_ustudio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the media_entity_ustudio module.
    case 'help.page.media_entity_ustudio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Ustudio Media Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function media_entity_ustudio_theme() {
  return [
    'media_entity_ustudio' => [
      'variables' => [
        'embed' => NULL,
        'destination' => NULL,
        'video' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hooK_form_FORM_ID_alter().
 */
function media_entity_ustudio_form_media_ustudio_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  media_entity_ustudio_alter_media_form($form, $form_state);
}
function media_entity_ustudio_form_media_ustudio_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  media_entity_ustudio_alter_media_form($form, $form_state);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter()
 */
function media_entity_ustudio_alter_media_form(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  dpm('form alter');
  $values = $form_state->getValues();
  dpm($values);
//  $form['embed_code']['#value'] = $values['ustudio_upload'][0]['upload']['link'];
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function media_entity_ustudio_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() == 'media' && $bundle == 'ustudio') {
    $fields['ustudio_upload'] = BaseFieldDefinition::create('ustudio_upload')
      ->setLabel(t('uStudio Upload'))
      ->setTranslatable(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'ustudio_upload',
        'weight' => 30,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setComputed(FALSE);

    return $fields;
  }
}